apiVersion: v1
data:
  dbname: library
  host: mysql.database:3306 #mysql.database.svc.cluster.local
  dbuser: root
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: restapi-cm
  namespace: restapi
